<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="asus" failures="0" tests="2" name="dataProvider.ValidateNeoStoxUserNameUsingPropertyFile" time="0.000" errors="2" timestamp="2023-01-11T16:52:01 IST" skipped="0">
  <testcase classname="dataProvider.ValidateNeoStoxUserNameUsingPropertyFile" name="validateUserName" time="0.000">
    <error message="
Method public void dataProvider.ValidateNeoStoxUserNameUsingPropertyFile.validateUserName(java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException,org.apache.poi.EncryptedDocumentException,java.io.IOException requires a @DataProvider named : loginDetailsforValidateUserName" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method public void dataProvider.ValidateNeoStoxUserNameUsingPropertyFile.validateUserName(java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException,org.apache.poi.EncryptedDocumentException,java.io.IOException requires a @DataProvider named : loginDetailsforValidateUserName
at org.testng.internal.Parameters.findDataProvider(Parameters.java:561)
at org.testng.internal.Parameters.handleParameters(Parameters.java:772)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- validateUserName -->
  <system-out/>
  <testcase classname="dataProvider.ValidateNeoStoxUserNameUsingPropertyFile" name="validateACBalance" time="0.000">
    <error message="
Method public void dataProvider.ValidateNeoStoxUserNameUsingPropertyFile.validateACBalance(java.lang.String,java.lang.String) throws org.apache.poi.EncryptedDocumentException,java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : loginDetailForValidateAccountBalance" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method public void dataProvider.ValidateNeoStoxUserNameUsingPropertyFile.validateACBalance(java.lang.String,java.lang.String) throws org.apache.poi.EncryptedDocumentException,java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : loginDetailForValidateAccountBalance
at org.testng.internal.Parameters.findDataProvider(Parameters.java:561)
at org.testng.internal.Parameters.handleParameters(Parameters.java:772)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- validateACBalance -->
  <system-out/>
</testsuite> <!-- dataProvider.ValidateNeoStoxUserNameUsingPropertyFile -->
